### ISSUE TITLE
Cần hướng dẫn cấu hình Server upload file

### ISSUE THREAD

**Issue by thanhchunghti** [nukeviet/module-download#102]
Anh có thể làm 1 bài hướng dẫn cấu hình Server upload file mục File server được ko ạ? Chứ dùng trên 1 host giờ nặng quá.
Em cảm ơn

**Comment by hoaquynhtim99** [comment]
Phần server đó độc lập với module download này nhé bạn. Đó là chức năng lớn, độc quyền chứ không miễn phí.
