### ISSUE TITLE
Bổ sung chức năng trong quản trị

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/module-download#126]
- Cấu hình module cần bổ sung selectbox "Kiểu sắp xếp file mặc định trong quản trị" có thể chọn:
    - Giảm dần theo ngày thêm (Mặc định cài module là cái này)
    - Tăng dần theo tên file
- Tại trang chủ module trong quản trị bổ sung order vào các mục Tên file, Thời gian đăng, xem, tải, bình. Order mặc định theo cấu hình ở ý bên trên.

**Comment by hqc210185** [comment]
đã hoàn thành
