### ISSUE TITLE
Góp ý về Phương án hiển thị trên trang chủ

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/module-download#18]
Mình thấy có thay đổi trong cách thể hiện trên trang chủ và từng chủ đề. Về phương án chọn theo "Danh sách" thấy nó còn đơn điệu và không đẹp mắt lắm, có thể thể hiện như demo thì khoa học và đẹp mắt hơn, Thanks đội code
![2015-09-16_074142](https://cloud.githubusercontent.com/assets/10916826/9893821/fc5672a6-5c46-11e5-98f3-778d131c558a.png)

**Comment by hoaquynhtim99** [comment]
Phần này bạn cần có thể tự thiết kế lại giao diện nhé
