### ISSUE TITLE
Hỏi

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/module-download#19]
Trong block news file có 1 thuộc tính thể hiện hình ảnh, nhưng mình không biết điền vào đó là gì? xin được hướng dẫn. Cảm ơn đội code
![faststoneeditor](https://cloud.githubusercontent.com/assets/10916826/9893973/dcc19180-5c48-11e5-9ffb-69dfbac22b0b.png)

**Comment by htuyen1994** [comment]
bỏ đi do không sử dụng
