### ISSUE TITLE
Lỗi hiển thị của module download khi cấu hình

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/module-download#24]
- Khi cấu hình "Chuyên mục, tập tin khác nằm bên dưới" thì click vào chề sẽ lỗi ERR_CONTENT_DECODING_FAILED
- Khi cấu hình" Tập tin mới và danh sách lên trên cũng lỗi "ERR_CONTENT_DECODING_FAILED"

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/module-download/commit/343455c9c8b0dcec4dc5c207d5c9d450defd9b6b
