### ISSUE TITLE
Điều hướng tính năng upload bên ngoài site

### ISSUE THREAD

**Issue by vuthao** [nukeviet/module-download#34]
Bên ngoài site có nút upload, nếu là quản trị nên đẩy link này vào khi vực quản trị để người quản trị có nhiều lựa chọn hơn, và không phải duyệt lại bài của mình.

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/module-download/commit/e89ab8989ecd8c83bf479de85dd2c443f77c5780
