### ISSUE TITLE
Hiện tại đã cập nhật lên bản mới nhất thấy phát hiện lỗi download.js

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/module-download#36]
khi vào module download có cảnh báo lỗi Uncaught TypeError: $(...).validate is not a function từ file download.js và nút tích chọn 5 sao thành hình tròn thay vì mặc định là icon sao

**Comment by ThinhNguyenVB** [comment]
bổ sung, sắp xếp dạng danh sách mới lên trên có cấu hình upload thì nút "Tải lên" không có link up mà chỉ là link trang chủ module

**Comment by hongoctrien** [comment]
Fixed: https://github.com/nukeviet/module-download/pull/37
