### ISSUE TITLE
block new_file: sửa lại phần kiểm tra file tpl

### ISSUE THREAD

**Issue by htuyen1994** [nukeviet/module-download#4]
Đoạn này đang sử dụng  `$module_info['template']`

```
if( file_exists( NV_ROOTDIR . '/themes/' . $module_info['template'] . '/modules/' . $file . '/block_new_files.tpl' ) )
{
	$block_theme = $module_info['template'];
}
else
{
	$block_theme = 'default';
}

```
thay nó bằng `$global_config['module_theme']` để có thể sử dụng file tpl ở theme khác

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/module-download/commit/e2c8d1790424bdffd6cf1142d3a93a744bb19076
