### ISSUE TITLE
Module download nv4 không tạo được module ảo và global block catalogs

### ISSUE THREAD

**Issue by ongOkie** [nukeviet/module-download#45]
Chào mọi người trong Github!
Khi sử dụng Module Download v4.0.19
Mình thấy module này không tạo thêm được module ảo.
Khi mình thêm chủ đề trong module, rồi tạo block quản trị không thấy phần chọn danh mục. mặc dù đã thử tất cả block của module download!
Mọi người xem và giúp đỡ mình với !

**Comment by vuthao** [comment]
Bản đang hiện tại trên kho code đã khắc phục các vấn đề này nhé bạn, cần cài mới do thay đổi khá nhiều, nếu nâng cấp xem tại: https://github.com/nukeviet/module-download/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-n%C3%A2ng-c%E1%BA%A5p-module-download-l%C3%AAn-phi%C3%AAn-b%E1%BA%A3n-4.0.23

**Comment by ongOkie** [comment]
phiên bản nâng cấp 4.0.23 không tương thích vs code nv4.0.21 anh ạ!
em cài vào nó báo lỗi tùm lum và khi tải file về, trả link  giá trị rỗng "javascript:void(0);"

**Comment by ongOkie** [comment]
anh có bản nào tương thích vs 4.0.21 không cho em xin vs ạ!
nukeviet.vn em không vào được ạ :((
