### ISSUE TITLE
Mudule Download cài đặt trên Nukeviet 4.0.25 Thông báo từ Hệ thống báo Nên chú ý và Lỗi cảnh báo

### ISSUE THREAD

**Issue by NukeVietCMS** [nukeviet/module-download#47]
Cài đặt bằng phần Mở rộng trong quảng trị thì khi vào cấu hình của module nhận được như sau:

Thông báo từ Hệ thống
Nên chú ý	Nên chú ý: Undefined index: indexfile in file /modules/download/admin/config.php on line 143
Nên chú ý	Nên chú ý: Undefined index: indexfile in file /modules/download/admin/config.php on line 152
Nên chú ý	Nên chú ý: Undefined index: viewlist_type in file /modules/download/admin/config.php on line 162
Lỗi cảnh báo	Lỗi cảnh báo: explode() expects parameter 2 to be string, array given in file /modules/download/admin/config.php on line 168
Lỗi cảnh báo	Lỗi cảnh báo: in_array() expects parameter 2 to be array, null given in file /modules/download/admin/config.php on line 171

**Comment by htuyen1994** [comment]
hiện tại bản NK mới  + module download mới nhất k có lỗi này,

**Comment by hoannhv** [comment]
Thông báo từ Hệ thống
Nên chú ý: Undefined index: indexfile in file /modules/download/admin/config.php on line 143
Nên chú ý: Undefined index: indexfile in file /modules/download/admin/config.php on line 152
Nên chú ý: Undefined index: viewlist_type in file /modules/download/admin/config.php on line 162
Lỗi cảnh báo: explode() expects parameter 2 to be string, array given in file /modules/download/admin/config.php on line 168
Lỗi cảnh báo: in_array() expects parameter 2 to be array, null given in file /modules/download/admin/config.php on line 171

Lỗi chứ sao không, mình cũng bị y chang nhé. Bản develop luôn đó. Khi đưa ra menu truy cập vào cũng lỗi máy chủ 500.

**Comment by hoaquynhtim99** [comment]
Bạn tải bản mới nhất để fix lỗi này nhé
