### ISSUE TITLE
Lỗi 500 không tìm thấy trang

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/module-download#48]
trong admin báo lỗi 
Nên chú ý: Undefined index: download in file /modules/download/admin/add.php on line 300
ra ngoài site báo lỗi 500. Đã cài đi cài lại nhiều lần nhưng vẫn như vậy. 

thử trên wamsever
Apache Version	Apache/2.4.9 (Win64) PHP/5.5.12

**Comment by htuyen1994** [comment]
Bản mới nhất k thấy lỗi.
