### ISSUE TITLE
nâng cấp module download nv3 qua bản mới báo lỗi thế này

### ISSUE THREAD

**Issue by thuanthuyen** [nukeviet/module-download#49]
Thông báo từ Hệ thống

Nên chú ý Nên chú ý: Undefined index: is_addfile in file /modules/download/functions.php on line 40

Nên chú ý Nên chú ý: Undefined index: per_page_child in file /modules/download/funcs/viewcat.php on line 42

Lỗi cảnh báo Lỗi cảnh báo: Division by zero in file /includes/functions.php on line 1217

Nên chú ý Nên chú ý: Undefined index: viewlist_type in file /modules/download/theme.php on line 121

**Comment by htuyen1994** [comment]
Lỗi này là do chưa nâng cấp csdl
