### ISSUE TITLE
Lỗi js ngay tại trang chủ của module download

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/module-download#5]
Hiện tại khi truy cập vào module download ngay tại trang main thì hiện ra lỗi sau
"Uncaught TypeError: $(...).rating is not a function"
Nếu di chuyển đoạn jquery // Viewfile trong file download.js từ sang file viewfile.tpl thì hiện tượng này hết.
Nguyên nhân trong đoạn js là từ $('.hover-star').rating()

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/module-download/commit/9435c7e2cd23e70ac8bddd2fe373ea191035bca9
