### ISSUE TITLE
Help! Lỗi cài trên 4.27

### ISSUE THREAD

**Issue by hpleduit** [nukeviet/module-download#54]
Thông báo từ Hệ thống

Nên chú ý Nên chú ý: Undefined variable: array_cats in file /modules/download/funcs/main.php on line 150

Lỗi cảnh báo Lỗi cảnh báo: Invalid argument supplied for foreach() in file /modules/download/theme.php on line 34

**Comment by hoaquynhtim99** [comment]
Fixed: https://github.com/nukeviet/module-download/commit/573e6792866838ec0bd8b35182a9d29e4146c7cb
