### ISSUE TITLE
Thiếu file content.tpl

### ISSUE THREAD

**Issue by thuanthuyen** [nukeviet/module-download#56]
[XTemplate]
/home/thiendang/domains/thiendang.net/public_html/themes/modules/download/content.tpl does not exist

**Comment by hoaquynhtim99** [comment]
#55

**Comment by thuanthuyen** [comment]
https://cloud.githubusercontent.com/assets/2588604/14981365/ed43931c-1158-11e6-857c-0b6fce27fe28.jpg
phần tải file nè hoaquynhtim

**Comment by hoaquynhtim99** [comment]
Bạn check lại với phiên bản mới nhất xem sao mình check không thấy cái này. Đối với thành viên upload bên ngoài thì file sử dụng là upload.tpl
