### ISSUE TITLE
Lỗi tìm kiếm modules download

### ISSUE THREAD

**Issue by anhutbeo** [nukeviet/module-download#59]
Chức năng tìm kiếm trên site sẽ bị lỗi toàn bộ nếu có cài thêm modules download, nếu kg cài thì kg sao, hoặc bỏ file search.php trong modules thì site hoạt động bình thường

![loi](https://cloud.githubusercontent.com/assets/10916826/15417772/7ed83c4c-1e83-11e6-9358-5841aa7a7e1d.png)

**Comment by quangcuong** [comment]
Tôi cũng bị lỗi tìm kiếm khi cài Module download:
- Cài vào vẫn tìm kiếm được
- Khi thêm chủ đề trong module download thì bị lỗi như trên
  Môi trường thử nghiệm: 
- Localhost (dùng vertrigo)
- Bản nuke 4.0.29
- Module download bản 4.0.29
  (Chỉ cài thêm module download)

**Comment by hoaquynhtim99** [comment]
Chức năng tìm kiếm đã được sửa tại: https://github.com/nukeviet/module-download/commit/1f25e7e7fd76e36355268b83cb3206185ca95fe9, các bạn có thể tải file sau để fix cho site của mình trước khi module download ra phiên bản mới https://raw.githubusercontent.com/nukeviet/module-download/1f25e7e7fd76e36355268b83cb3206185ca95fe9/modules/download/search.php
