### ISSUE TITLE
Vì một lý do nào đó, chủ đề mới đã không được tạo !

### ISSUE THREAD

**Issue by songnhien** [nukeviet/module-download#63]
Em bị lỗi "Vì một lý do nào đó, chủ đề mới đã không được tạo !" bản nukeviet mới nhất 4.0.29 ạ.
Nên chú ý: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'groups_onlineview' in 'field list'

**Comment by hoaquynhtim99** [comment]
Lỗi này do bạn nâng cấp module theo kiểu ghi đè mà không chạy tool update, cài mới hoặc chạy tool update sẽ không bị bạn nhé
