### ISSUE TITLE
Lỗi không tìm kiếm được trên site (dạng quick search)

### ISSUE THREAD

**Issue by nguyennampotter** [nukeviet/module-download#65]
Hiện nay tôi đang gặp lỗi khi cài đặt modul download này thì khi gõ ô tìm kiếm tại trang chủ thì bị trang trắng. Một số thành viên trên diễn đàn cũng bị tình trạng này, khi gỡ bỏ modul download thì tìm kiếm lại bình thường.
Xin hỏi cách khắc phục. Thanks

**Comment by hoaquynhtim99** [comment]
Lỗi này đã được fix bạn có thể tải file https://github.com/nukeviet/module-download/blob/develop/modules/download/search.php để ghi đè lên file bị lỗi.
