### ISSUE TITLE
Lỗi đường dẫn không hợp lệ

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/module-download#67]
> 3. tôi cũng cài module dơnload nhưng khi chen một liên kết từ onerive thì báo đường dẫn không hơp lệ nhưng khi lấy đường dẫn từ google rai thì bình thường mặt dù mình đã lấy đường dẫn của onerive truy cập vào thì nó vaaxn chạy bình thường và đây là một link từ onerive để ban quản ttrij xem tesst thử nhe: https://1drv.ms/u/s!Auc_7P8QuDYpgV7CbudSljZG8f-g

Có người báo lỗi này, đưa lên đây đội code kiểm tra giúp

**Comment by hoaquynhtim99** [comment]
Phần này đã được giải quyết ở https://github.com/hoaquynhtim99/nukeviet/commit/a4144a289639c40dd256b1d78468310336500960, sẽ đc tự sửa lỗi khi cập nhật lên NukeViet bản tới
