### ISSUE TITLE
Cập nhật hàm nv_download_file

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/module-download#68]
https://github.com/nukeviet/module-download/blob/develop/themes/default/js/download.js#L85

Tham số `fr` không được sử dụng

**Comment by hoaquynhtim99** [comment]
Phần này để thế tạm thời không ảnh hưởng gì nếu sửa sẽ ảnh hưởng tới các giao diện khác khi cập nhật lên bản mới. @mynukeviet xem thử có nhất trí không nhé.

**Comment by mynukeviet** [comment]
Ok
