### ISSUE TITLE
Cấu hình trang đăng file ở ngoài.

### ISSUE THREAD

**Issue by vuthao** [nukeviet/module-download#70]
Thêm cấu hình các trường đăng (cả ở ngoài site, và admin) với các trường không bắt buộc:

1.  Trường nào hiển thị, không hiển thị,  Nếu hiển thị có bắt buộc nhập hay không cho trang ngoài site và cho trang admin.
1. Khi chọn phần:  Thuộc chủ đề, hiện tại đang hiển thị cả chủ đề cha và con, Ví dụ site có 12 chủ đề cha và 12 chủ đề con việc lựa chọn này là bất khả thi bởi có tới 144 chủ đề. Cần sửa lại:
- Chỉ hiển thị chủ đề cha, sau khi chọn xong chủ đề cha mới hiển thị chủ đề con.
- Xem khi di chuyển chuột đến chủ đề chính (Lúc đang lựa chọn) thì xem có thể cho hiển thị các chủ đề con của nó được không, ví dụ ở dạng tooltip.

**Comment by hoaquynhtim99** [comment]
Đã thêm https://github.com/nukeviet/module-download/commit/72b8e85e7aff4a9baea69ac3403d555333a49c3a

**Comment by vuthao** [comment]
Hiện tại vẫn còn phần: Nguồn bên ngoài, Ly do quản trị chỉ muốn khách hàng tải file lên server của mình, bởi dùng link của bên ngoài có thể hỏng.

Nếu đã là thành viên thì dòng: Tên bạn nên ẩn đi.

**Comment by vuthao** [comment]
Khi trong module cấu hình
![untitled](https://cloud.githubusercontent.com/assets/2491500/24337495/eabd8e6a-12c7-11e7-8603-c82358e980bc.png)

Nhưng bên ngoài site cái này vẫn fix cứng theo lang, nên kiểm tra nếu có cấu hình của op khách tên op thì nên dùng cấu hình này
![untitled2](https://cloud.githubusercontent.com/assets/2491500/24337520/3c13219e-12c8-11e7-989b-828c6e0a64c5.png)

**Comment by hoaquynhtim99** [comment]
Đã thêm https://github.com/nukeviet/module-download/commit/e14ba9b46fc5dcc08b1b9eb4baf1ba93e85e5110
