### ISSUE TITLE
Cấu hình ai được đăng tài liệu theo chủ đề

### ISSUE THREAD

**Issue by vuthao** [nukeviet/module-download#71]
Trong phần quản lý chủ đề, với mối chủ đề có phần:

1.  Quyền xem mô tả 
2.  Quyền xem trực tuyến (Nếu hỗ trợ) 
3.  Quyền tải file 

Cần bổ sung thêm quyền, cho phép tải file lên (Chức năng đăng ngoài site). bởi có những chủ đề không muốn cho các thành viên tải lên.

**Comment by hoaquynhtim99** [comment]
Đã thêm https://github.com/nukeviet/module-download/commit/72b8e85e7aff4a9baea69ac3403d555333a49c3a

**Comment by vuthao** [comment]
@hoaquynhtim99 mình vẫn chưa thấy phần cấu hình cho arr_dis_ur_linkdirect

**Comment by hoaquynhtim99** [comment]
https://github.com/nukeviet/module-download/commit/e14ba9b46fc5dcc08b1b9eb4baf1ba93e85e5110 đây nha anh
