### ISSUE TITLE
Lỗi kiểm duyệt file

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/module-download#72]
- Thành viên B đăng tài liệu và chờ duyệt duyệt
- Người quản trị A kiểm duyệt file cho B gửi đến

**Lỗi:** Lúc này người đăng file mới là A đăng chứ không phải B

**Comment by vuthao** [comment]
@hoaquynhtim99 khi sửa lại module, sửa lại cả phần này nhé.

**Comment by mynukeviet** [comment]
Đã sửa https://github.com/nukeviet/module-download/pull/73/commits/125ded75071581e3538ec79e9e89cdfcfe1d7a3c
