### ISSUE TITLE
Vấn đề file download sau khi tải

### ISSUE THREAD

**Issue by quangcuong** [nukeviet/module-download#76]
Khi úp một file trực tiếp lên host, như đường dẫn ở dưới
`/..../uploads/download/2016_09/files/5_danh-sach-hs-so-diem-nam-hoc-2016-2017-1.rar`

Sau đó download về nó bị trường hợp như sau: 
File download: 5_danh-sach-hs-so-diem-nam-hoc-2016-2017-1.rar 
--> tiến hành giải nén thf nó ra như thế này:
`home\thptngu4\public_html\ntb\uploads\download\2016_09\files\5_danh-sach-hs-so-diem-nam-hoc-2016-2017-1.rar`
mà không phải là : 5_danh-sach-hs-so-diem-nam-hoc-2016-2017-1
..................................
+ Module download hiện đang dùng là bàn mới nhất: 4.1.02
...................................
Trường hợp này khắc phục thế nào?
HÌnh mô tả:
![file up len host](https://cloud.githubusercontent.com/assets/14310636/26111340/05587d14-3a7f-11e7-90c3-f995b0e0ea06.JPG)
![loi md download](https://cloud.githubusercontent.com/assets/14310636/26111341/066986da-3a7f-11e7-8109-4a7c8c01d7e2.JPG)

**Comment by hoaquynhtim99** [comment]
Lỗi này đã được fix ở https://github.com/nukeviet/module-download/commit/991347cfbd7f1bb8008ed0af2fa8abe37c306479 bạn có thể tải trực tiếp file đó về ghi đè hoặc đợi bản cập nhật kế tiếp
