### ISSUE TITLE
Lỗi thống kê số lần tải về module Download

### ISSUE THREAD

**Issue by nambmtk1993** [nukeviet/module-download#77]
Module download bản mới nhất khi dùng xảy ra tình trạng: 
Khi download file bằng IDM, Coccoc bắt link thì thống kê số lần download của file bị tăng lên 4 hoặc 5 lượt chứ không phải thêm một lượt như thông thường.

Lỗi được thông báo tại[ bài viết](https://nukeviet.vn/vi/forum/Loi-nghiem-trong-module-download-Nho-cac-bac-sua-voi-t43228-p185746/#p185746)

**Comment by hoaquynhtim99** [comment]
Mình không khuyến khích việc sửa cái này

**Comment by vuthao** [comment]
@hoaquynhtim99 việc này do các trình download nó tạo nhiều session download cùng lúc.

Anh đã sửa lại để nó chỉ đếm lầm đầu tiên ứng với mỗi file: https://github.com/nukeviet/module-download/commit/afed81fabafd32ccdc475fb7e94a3657781d05d9

**Comment by hoaquynhtim99** [comment]
@vuthao sao cái đó sinh ra `copy_document` anh? Chưa thấy có ghi chú CSDL sau này nâng cấp sẽ bỏ sót mất

**Comment by vuthao** [comment]
Vào cấu hình nó sẽ tự động sinh ra. Lát anh sẽ viết bổ sung.
