### ISSUE TITLE
Lỗi hiện form comment trong module download

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/module-download#8]
Hiện tại trong đoạn code sau ở file viewfile.php code có nhầm lẫn giữa NV_COMM_ALLOWED và NV_COMM_AREA để làm diều kiện so sánh quyền thảo luận

define( 'NV_COMM_ID', $row['id'] );
	define( 'NV_COMM_ALLOWED', nv_user_in_groups( $row['groups_comment'] ) );
	// Kiem tra quyen dang binh luan
	$allowed = $module_config[$module_name]['allowed_comm'];
	if( $allowed == '-1' )
	{
		// Quyen han dang binh luan theo bai viet
		$allowed = ( defined( 'NV_COMM_ALLOWED' ) ) ? NV_COMM_ALLOWED : $module_config[$module_name]['setcomm'];
	}
	define( 'NV_PER_PAGE_COMMENT', 5 );//per_page_comment
	require_once NV_ROOTDIR . '/modules/comment/comment.php';
	$area = ( defined( 'NV_COMM_AREA' ) ) ? NV_COMM_AREA : 0;
	$checkss = md5( $module_name . '-' . $area . '-' . NV_COMM_ID . '-' . $allowed . '-' . NV_CACHE_PREFIX );

    $content_comment = nv_comment_module( $module_name, $checkss, $area, NV_COMM_ID, $allowed, 1 );

**Comment by hongoctrien** [comment]
Fixed: https://github.com/hongoctrien/module-download/commit/e189cdbefdef9e850627bdaa1b0eee57548fb98b
