### ISSUE TITLE
Lỗi  chức năng tìm kiếm

### ISSUE THREAD

**Issue by vuthao** [nukeviet/module-download#80]
Block tìm kiếm của module chỉ hiển thị chuyên mục chính, không hiển thị chuyên mục con.

Khi tìm kiếm thì nó chỉ tìm kiếm chuyên mục chính mà không tìm kiếm chuyên mục con.

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/module-download/commit/59cf4d6018b1862a44a856555e68ad7419cd8c54
