### ISSUE TITLE
Thiết lập thêm cấu hình bỏ một số trường ở form nhập tài liệu

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/module-download#81]
Cấu hình mặc định lại các dữ liệu mẫu ở mức tối thiểu thông tin để nhập đỡ rối (Ví dụ thông tin tác giá, bản quyền ….)

**Comment by thuvp1995** [comment]
Cấu hình này đã có trong phần cuối cùng của cấu hình module download
