### ISSUE TITLE
Lỗi liên kết sửa file

### ISSUE THREAD

**Issue by vuthao** [nukeviet/module-download#83]
Ở ngoài site khi admin đăng nhập thì có link:
https://domain.vn/admin/index.php?language=vi&nv=download&edit=1&id=65

Nhưng link đúng là:
https://domain.vn/admin/index.php?language=vi&nv=download&op=content&id=65

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/module-download/commit/23df86ef7a92beba4bee5733f9af20184cd07a4d
