### ISSUE TITLE
Lỗi url khi tắt rewrite

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/module-download#87]
Khi tắt rewrite thì click vào url xem chi tiết hoặc xem chủ đề bị lỗi

```
http://module-download.vn/index.php?language=vi&amp;nv=download&amp;op=g-rtg-ftdg-tfg/srf-drzg-drg.html
```

**Comment by vuthao** [comment]
@mynukeviet em đã sửa cái này, tuy nhiên cái này theo anh phải sửa vào cả NukeViet để khắc phục các module khác.

@hoaquynhtim99 xem xét nhé.

**Comment by mynukeviet** [comment]
ok a.

**Comment by hoaquynhtim99** [comment]
Đã sửa ở https://github.com/nukeviet/nukeviet/pull/2715
