### ISSUE TITLE
modules\download\language\admin_vi.php cùng một nội dung 215, 223

### ISSUE THREAD

**Issue by NukeVlad** [nukeviet/module-download#89]
modules\download\language\admin_vi.php cùng một nội dung
строка: 215
$lang_module['alias_search'] = 'Để hiển thị các tags khác, bạn dùng chức năng tìm kiếm để hiển thị nhiều kết quả hơn';
строка: 223
$lang_module['alias_search'] = 'Để hiển thị các tags khác, bạn dùng chức năng tìm kiếm để hiển thị nhiều kết quả hơn';

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/module-download/commit/313f84155641fdcb0c1d27a1c58748829b7b9bc3
