### ISSUE TITLE
Tên file dài trong khi nối nhau nên trình duyệt không tự động xuống hàng

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/module-download#96]
https://onthicongchuc.vn/tai-nguyen/Kien-thuc-chuyen-nganh/BO-CAU-HOI-CHUYEN-NGANH-VAN-PHONG-THONG-KE-Dung-cho-thi-tuyen-cong-chuc-cap-xa-nam-2018.html

Tên file dài trong khi nối nhau nên trình duyệt không tự động xuống hàng, nên trên di động giao diện bị tràn, google cảnh báo `Chữ quá nhỏ để đọc`

![image](https://user-images.githubusercontent.com/6407361/62361962-3a2ee200-b546-11e9-983b-2400350285c3.png)

**Comment by thehung** [comment]
Có lẽ nên bật cái alias để có thể chủ động sửa URL cũng như tên file cho ngắn nhỉ @hoaquynhtim99 @mynukeviet

**Comment by hoaquynhtim99** [comment]
Cái này chắc thêm `text-overflow: ellipsis;` là ổn, giờ mà thêm alias của file là có nhiều vấn đề lắm
